---
- name: Playbook to create a user
  hosts: ans01
  become: yes
  vars_files:
    - users_list.yml
  tasks:
    - name: Create user
      user:
        name: "{{ item.name }}"
        state: present
      loop: "{{ users }}"
